update

diff --git a/.github/workflows/adguardhome.yml b/.github/workflows/adguardhome.yml
--- a/.github/workflows/adguardhome.yml
+++ b/.github/workflows/adguardhome.yml
@@ -91,7 +91,11 @@ jobs:
               exit 1
           fi
           # install luci-app-adguardhome IPK
-          opkg install *.ipk
+          echo "Installing luci-app-adguardhome ipk"
+          if ! opkg install *.ipk 2>/dev/null; then
+            echo "Package install failed"
+            exit 1
+          fi
           # update latest AdGuardHome Core
           cp AdGuardHome/AdGuardHome /usr/bin/AdGuardHome
           chmod +x /usr/bin/AdGuardHome
